# Generated by Django 3.2.8 on 2021-10-20 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        ('announcement', '0005_alter_announcement_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 13, 30, 3, 557908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='workspace',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
    ]
