# Generated by Django 3.2.8 on 2021-10-20 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_auto_20211020_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='workspace',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 13, 43, 51, 701383, tzinfo=utc)),
        ),
    ]
