# Generated by Django 3.2.6 on 2021-10-28 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0012_auto_20211028_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 21, 33, 7, 289580, tzinfo=utc)),
        ),
    ]
