# Generated by Django 3.2.8 on 2021-10-14 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_announcement_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 20, 48, 10, 30909, tzinfo=utc)),
        ),
    ]
