# Generated by Django 3.2.6 on 2021-10-28 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        ('announcement', '0007_auto_20211020_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 13, 2, 4, 987305, tzinfo=utc)),
        ),
    ]
