# Generated by Django 3.2.6 on 2021-10-28 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0009_auto_20211028_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 13, 7, 33, 335199, tzinfo=utc)),
        ),
    ]
