# Generated by Django 3.2.6 on 2021-10-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.TextField(),
        ),
    ]
